// Generated by gencpp from file game_control/GetUserScore.msg
// DO NOT EDIT!


#ifndef GAME_CONTROL_MESSAGE_GETUSERSCORE_H
#define GAME_CONTROL_MESSAGE_GETUSERSCORE_H

#include <ros/service_traits.h>


#include <game_control/GetUserScoreRequest.h>
#include <game_control/GetUserScoreResponse.h>


namespace game_control
{

struct GetUserScore
{

typedef GetUserScoreRequest Request;
typedef GetUserScoreResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetUserScore
} // namespace game_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::game_control::GetUserScore > {
  static const char* value()
  {
    return "e10e2705e269839872c95ff0a89588d4";
  }

  static const char* value(const ::game_control::GetUserScore&) { return value(); }
};

template<>
struct DataType< ::game_control::GetUserScore > {
  static const char* value()
  {
    return "game_control/GetUserScore";
  }

  static const char* value(const ::game_control::GetUserScore&) { return value(); }
};


// service_traits::MD5Sum< ::game_control::GetUserScoreRequest> should match
// service_traits::MD5Sum< ::game_control::GetUserScore >
template<>
struct MD5Sum< ::game_control::GetUserScoreRequest>
{
  static const char* value()
  {
    return MD5Sum< ::game_control::GetUserScore >::value();
  }
  static const char* value(const ::game_control::GetUserScoreRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::game_control::GetUserScoreRequest> should match
// service_traits::DataType< ::game_control::GetUserScore >
template<>
struct DataType< ::game_control::GetUserScoreRequest>
{
  static const char* value()
  {
    return DataType< ::game_control::GetUserScore >::value();
  }
  static const char* value(const ::game_control::GetUserScoreRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::game_control::GetUserScoreResponse> should match
// service_traits::MD5Sum< ::game_control::GetUserScore >
template<>
struct MD5Sum< ::game_control::GetUserScoreResponse>
{
  static const char* value()
  {
    return MD5Sum< ::game_control::GetUserScore >::value();
  }
  static const char* value(const ::game_control::GetUserScoreResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::game_control::GetUserScoreResponse> should match
// service_traits::DataType< ::game_control::GetUserScore >
template<>
struct DataType< ::game_control::GetUserScoreResponse>
{
  static const char* value()
  {
    return DataType< ::game_control::GetUserScore >::value();
  }
  static const char* value(const ::game_control::GetUserScoreResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAME_CONTROL_MESSAGE_GETUSERSCORE_H
