// Generated by gencpp from file game_control/GetUserScoreRequest.msg
// DO NOT EDIT!


#ifndef GAME_CONTROL_MESSAGE_GETUSERSCOREREQUEST_H
#define GAME_CONTROL_MESSAGE_GETUSERSCOREREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace game_control
{
template <class ContainerAllocator>
struct GetUserScoreRequest_
{
  typedef GetUserScoreRequest_<ContainerAllocator> Type;

  GetUserScoreRequest_()
    : user_name()  {
    }
  GetUserScoreRequest_(const ContainerAllocator& _alloc)
    : user_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _user_name_type;
  _user_name_type user_name;





  typedef boost::shared_ptr< ::game_control::GetUserScoreRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::game_control::GetUserScoreRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetUserScoreRequest_

typedef ::game_control::GetUserScoreRequest_<std::allocator<void> > GetUserScoreRequest;

typedef boost::shared_ptr< ::game_control::GetUserScoreRequest > GetUserScoreRequestPtr;
typedef boost::shared_ptr< ::game_control::GetUserScoreRequest const> GetUserScoreRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::game_control::GetUserScoreRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::game_control::GetUserScoreRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::game_control::GetUserScoreRequest_<ContainerAllocator1> & lhs, const ::game_control::GetUserScoreRequest_<ContainerAllocator2> & rhs)
{
  return lhs.user_name == rhs.user_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::game_control::GetUserScoreRequest_<ContainerAllocator1> & lhs, const ::game_control::GetUserScoreRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace game_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::game_control::GetUserScoreRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::game_control::GetUserScoreRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::game_control::GetUserScoreRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::game_control::GetUserScoreRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::game_control::GetUserScoreRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::game_control::GetUserScoreRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::game_control::GetUserScoreRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "159b36609af19853383ab1313ed185b0";
  }

  static const char* value(const ::game_control::GetUserScoreRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x159b36609af19853ULL;
  static const uint64_t static_value2 = 0x383ab1313ed185b0ULL;
};

template<class ContainerAllocator>
struct DataType< ::game_control::GetUserScoreRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "game_control/GetUserScoreRequest";
  }

  static const char* value(const ::game_control::GetUserScoreRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::game_control::GetUserScoreRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string user_name\n"
;
  }

  static const char* value(const ::game_control::GetUserScoreRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::game_control::GetUserScoreRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.user_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetUserScoreRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::game_control::GetUserScoreRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::game_control::GetUserScoreRequest_<ContainerAllocator>& v)
  {
    s << indent << "user_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.user_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAME_CONTROL_MESSAGE_GETUSERSCOREREQUEST_H
