// Generated by gencpp from file game_control/SetGameDifficultyResponse.msg
// DO NOT EDIT!


#ifndef GAME_CONTROL_MESSAGE_SETGAMEDIFFICULTYRESPONSE_H
#define GAME_CONTROL_MESSAGE_SETGAMEDIFFICULTYRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace game_control
{
template <class ContainerAllocator>
struct SetGameDifficultyResponse_
{
  typedef SetGameDifficultyResponse_<ContainerAllocator> Type;

  SetGameDifficultyResponse_()
    : success(false)  {
    }
  SetGameDifficultyResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetGameDifficultyResponse_

typedef ::game_control::SetGameDifficultyResponse_<std::allocator<void> > SetGameDifficultyResponse;

typedef boost::shared_ptr< ::game_control::SetGameDifficultyResponse > SetGameDifficultyResponsePtr;
typedef boost::shared_ptr< ::game_control::SetGameDifficultyResponse const> SetGameDifficultyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::game_control::SetGameDifficultyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::game_control::SetGameDifficultyResponse_<ContainerAllocator1> & lhs, const ::game_control::SetGameDifficultyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::game_control::SetGameDifficultyResponse_<ContainerAllocator1> & lhs, const ::game_control::SetGameDifficultyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace game_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::game_control::SetGameDifficultyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "game_control/SetGameDifficultyResponse";
  }

  static const char* value(const ::game_control::SetGameDifficultyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
"\n"
;
  }

  static const char* value(const ::game_control::SetGameDifficultyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetGameDifficultyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::game_control::SetGameDifficultyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::game_control::SetGameDifficultyResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GAME_CONTROL_MESSAGE_SETGAMEDIFFICULTYRESPONSE_H
