// Generated by gencpp from file game_control/SetGameDifficulty.msg
// DO NOT EDIT!


#ifndef GAME_CONTROL_MESSAGE_SETGAMEDIFFICULTY_H
#define GAME_CONTROL_MESSAGE_SETGAMEDIFFICULTY_H

#include <ros/service_traits.h>


#include <game_control/SetGameDifficultyRequest.h>
#include <game_control/SetGameDifficultyResponse.h>


namespace game_control
{

struct SetGameDifficulty
{

typedef SetGameDifficultyRequest Request;
typedef SetGameDifficultyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetGameDifficulty
} // namespace game_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::game_control::SetGameDifficulty > {
  static const char* value()
  {
    return "790cc17e982cca965724bd72418a57ae";
  }

  static const char* value(const ::game_control::SetGameDifficulty&) { return value(); }
};

template<>
struct DataType< ::game_control::SetGameDifficulty > {
  static const char* value()
  {
    return "game_control/SetGameDifficulty";
  }

  static const char* value(const ::game_control::SetGameDifficulty&) { return value(); }
};


// service_traits::MD5Sum< ::game_control::SetGameDifficultyRequest> should match
// service_traits::MD5Sum< ::game_control::SetGameDifficulty >
template<>
struct MD5Sum< ::game_control::SetGameDifficultyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::game_control::SetGameDifficulty >::value();
  }
  static const char* value(const ::game_control::SetGameDifficultyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::game_control::SetGameDifficultyRequest> should match
// service_traits::DataType< ::game_control::SetGameDifficulty >
template<>
struct DataType< ::game_control::SetGameDifficultyRequest>
{
  static const char* value()
  {
    return DataType< ::game_control::SetGameDifficulty >::value();
  }
  static const char* value(const ::game_control::SetGameDifficultyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::game_control::SetGameDifficultyResponse> should match
// service_traits::MD5Sum< ::game_control::SetGameDifficulty >
template<>
struct MD5Sum< ::game_control::SetGameDifficultyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::game_control::SetGameDifficulty >::value();
  }
  static const char* value(const ::game_control::SetGameDifficultyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::game_control::SetGameDifficultyResponse> should match
// service_traits::DataType< ::game_control::SetGameDifficulty >
template<>
struct DataType< ::game_control::SetGameDifficultyResponse>
{
  static const char* value()
  {
    return DataType< ::game_control::SetGameDifficulty >::value();
  }
  static const char* value(const ::game_control::SetGameDifficultyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GAME_CONTROL_MESSAGE_SETGAMEDIFFICULTY_H
